package com.example.administrator.myapplication.charts;

import android.os.Bundle;
import android.support.v7.app.AppCompatActivity;
import android.view.View;

import com.example.administrator.myapplication.R;

import java.util.ArrayList;
import java.util.List;

import lecho.lib.hellocharts.model.Axis;
import lecho.lib.hellocharts.model.AxisValue;
import lecho.lib.hellocharts.model.Column;
import lecho.lib.hellocharts.model.ColumnChartData;
import lecho.lib.hellocharts.model.SubcolumnValue;
import lecho.lib.hellocharts.util.ChartUtils;
import lecho.lib.hellocharts.view.ColumnChartView;

public class HelloChartsActivity extends AppCompatActivity {
    private ColumnChartView column_chart;
    private int mColumnNum = 9;


    @Override
    protected void onCreate(Bundle savedInstanceState) {
        super.onCreate(savedInstanceState);
        setContentView(R.layout.activity_hello_charts);
        column_chart = (ColumnChartView) findViewById(R.id.column_chart);
        findViewById(R.id.random).setOnClickListener(new View.OnClickListener() {
            @Override
            public void onClick(View v) {
                getColumnChartData();
            }
        });
        getColumnChartData();
    }


    private void getColumnChartData() {
        ColumnChartData mColumnChartData;
        int mSubColumnNum = 1;
        List<Column> mColumns = new ArrayList<>();
        List<SubcolumnValue> mValues;

        int maxNum = 0;

        for (int i = 0; i < mColumnNum; i++) {
            mValues = new ArrayList<>();
            for (int i1 = 0; i1 < mSubColumnNum; i1++) {
                SubcolumnValue mValue = new SubcolumnValue((float) (Math.random() * 30F + 5), ChartUtils.pickColor());
                if (mValue.getValue() > maxNum) {
                    maxNum = (int) mValue.getValue();
                }
                mValues.add(mValue);
            }
            Column mColumn = new Column(mValues); //一个柱状图中显示几个柱子，取决于每个Column中没mValues集合中的数据
//            mColumn.setHasLabels(true);
//            mColumn.setHasLabelsOnlyForSelected(true);
            mColumns.add(mColumn);
        }
        mColumnChartData = new ColumnChartData(mColumns);

        List<AxisValue> mAxisXValues = new ArrayList<>();
        List<AxisValue> mAxisYValues = new ArrayList<>();
        for (int i = 0; i < 9; i++) {
            mAxisXValues.add(new AxisValue(i).setLabel((i + 1) + "月"));
        }


        /**按照值的最高数值设置Y轴坐标*/
//        Log.e("TAG", "maxNum : " + maxNum);
//        for (int i = 0; i < 100; i += 5) {
//            mAxisYValues.add(new AxisValue(i).setLabel(i + ""));
//        }

        Axis mXBottom = new Axis(mAxisXValues);
        Axis mYLeft = new Axis();
        mYLeft.setHasLines(true);
//        mYLeft.hasLines();
//        mYLeft.setAutoGenerated(true);


        mXBottom.setName("月份");
        mYLeft.setName("步数");

        mColumnChartData.setAxisXBottom(mXBottom);
        mColumnChartData.setAxisYLeft(mYLeft);

        column_chart.setMaxZoom(2f);

        column_chart.setColumnChartData(mColumnChartData);
    }

}
